[package]
name = "cj-store"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.12.0" }
reqwest = { version = "0.12.18", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
